/**
 * Created by vincexie on 2017/3/29.
 */
function a(callback) {
  return new Promise((resolve,reject) => reject('出错'))
}
